name: sqlitequery
base: core22
summary: Lightweight cross-platform SQLite database explorer
description: |
  SQLite Query Analyzer is a lightweight and efficient desktop utility designed
  to simplify the process of managing SQLite databases.
  
  It provides an intuitive interface for executing queries and direct table editing,
  making database operations seamless and straightforward.
  
  Features:
  - Cross platform - Runs natively on Windows, MacOS, and Linux
  - Easy-to-use interface for executing SQL queries
  - Fast table data editing
  - Persists application state and reloads last session on startup
  - Export database schema as CREATE TABLE statements
  - Export data as an SQL script containing INSERT statements or as CSV files
  - Desktop color theme awareness with automatic switching between dark/light themes

version: '0.2.32'
grade: stable
confinement: strict
architectures:
  - amd64

apps:
  sqlitequery:
    command: usr/bin/sqlitequery
    desktop: usr/share/applications/sqlitequery.desktop
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - audio-playback
      - pulseaudio
      - opengl

parts:
  sqlitequery:
    plugin: cmake
    source: .
    source-subdir: src/project
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DEXECUTABLE_NAME=sqlitequery
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - qt6-base-dev
      - libqt6sql6-sqlite
      - imagemagick
    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - libqt6sql6
      - libqt6sql6-sqlite
      - libglu1-mesa
      - libgl1
      - libgl1-mesa-glx
      - qtwayland5
      - qt6-qpa-plugins
      - libfontconfig1
      - libfreetype6
      - libx11-6
      - libxcb1
      - libxext6
      - libglib2.0-0
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      cp $CRAFT_PART_BUILD/../resources/icon.ico $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/sqlitequery.ico
      cat > $CRAFT_PART_INSTALL/usr/share/applications/sqlitequery.desktop << EOF
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=SQLite Query Analyzer
      Comment=Lightweight cross-platform SQLite database explorer
      Icon=sqlitequery
      Exec=sqlitequery %F
      Terminal=false
      Categories=Development;Utility;Database;
      MimeType=application/vnd.sqlite3;application/x-sqlite3;
      Keywords=sqlite;database;sql;query;
      EOF
      convert $CRAFT_PART_BUILD/../resources/icon.ico -resize 256x256 $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/sqlitequery.png