name: sqlitequery
base: core22
summary: Lightweight cross-platform SQLite database explorer
description: |
  SQLite Query Analyzer is a lightweight and efficient desktop utility designed
  to simplify the process of managing SQLite databases.
  
  It provides an intuitive interface for executing queries and direct table editing,
  making database operations seamless and straightforward.
  
  Features:
  - Cross platform - Runs natively on Windows, MacOS, and Linux
  - Easy-to-use interface for executing SQL queries
  - Fast table data editing
  - Persists application state and reloads last session on startup
  - Export database schema as CREATE TABLE statements
  - Export data as an SQL script containing INSERT statements or as CSV files
  - Desktop color theme awareness with automatic switching between dark/light themes

version: 1.0.0
grade: stable
confinement: classic

apps:
  sqlitequery:
    command: bin/SQLiteQueryAnalyzer
    desktop: usr/share/applications/sqlitequery.desktop

parts:
  sqlitequery:
    plugin: dump
    source: linux
    source-type: local
    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - libqt6sql6
      - libqt6svg6
      - qt6-qpa-plugins
      - libgl1
      - libxcb1
      - libx11-6
      - libxau6
      - libxdmcp6
      - libfontconfig1
      - libxkbcommon0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxkbcommon-x11-0
