name: sqlitequery
base: core22
summary: Lightweight cross-platform SQLite database explorer
description: |
  SQLite Query Analyzer is a lightweight and efficient desktop utility designed
  to simplify the process of managing SQLite databases.
  
  It provides an intuitive interface for executing queries and direct table editing,
  making database operations seamless and straightforward.
  
  Features:
  - Cross platform - Runs natively on Windows, MacOS, and Linux
  - Easy-to-use interface for executing SQL queries
  - Fast table data editing
  - Persists application state and reloads last session on startup
  - Export database schema as CREATE TABLE statements
  - Export data as an SQL script containing INSERT statements or as CSV files
  - Desktop color theme awareness with automatic switching between dark/light themes

version: '0.2.32'
grade: stable
confinement: strict
architectures:
  - amd64

apps:
  sqlitequery:
    command: usr/bin/sqlitequery
    desktop: usr/share/applications/sqlitequery.desktop
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - browser-support
      - network
      - gsettings
      - opengl

parts:
  sqlitequery:
    plugin: qmake
    source: .
    source-subdir: project
    qmake-project-file: project/SQLiteAnalyzer.pro
    qmake-major-version: 6
    qmake-parameters:
      - CONFIG+=release
