name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
    - name: QMake
      run: qmake
      working-directory: src
    - name: Make
      run: make
      working-directory: src
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      working-directory: src
      with:
        name: SQLite Query Analyzer (Linux)
        path: |
          *.app
  
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
    - name: QMake
      run: qmake
      working-directory: src
    - name: Make
      run: make
      working-directory: src
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      working-directory: src
      with:
        name: SQLite QuerAnalyzer (MacOS)
        path: |
          *.app
  
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
    - name: QMake
      run: qmake
      working-directory: src
    - name: Make
      run: make
      working-directory: src
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      working-directory: src
      with:
        name: SQLite QuerAnalyzer (Windows)
        path: |
          *.app
