name: Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/linux*.yml'
      - '!src/project/*'
      - '!src/**/*.cpp'
      - '!src/**/*.h'
      - '!src/**/*.ui'
    branches:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/linux-template.yml
    with:
      version: '0.2.${{ github.run_number }}'