name: Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/linux.yml'
      - '!src/project/*'
      - '!src/**/*.cpp'
      - '!src/**/*.h'
      - '!src/**/*.ui'
    branches:
      - '*'

env:
  VERSION: '0.2.${{ github.run_number }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Version in code
      shell: pwsh
      run: |
        $version = (Get-Content -Path src/main.cpp -Raw) -replace '#define VERSION "1.0.0"', '#define VERSION "${{ env.VERSION }}"'
        $version | Set-Content -Path src/main.cpp
        cat src/main.cpp
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.0'
    - name: CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/sqlitequery .
        cmake --build . --config Release --parallel 32
        cmake --install . --config Release --prefix /tmp/sqlitequery
        tar -czf SQLiteQueryAnalyzer.tar.gz -C /tmp/sqlitequery .
      working-directory: src/project
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SQLiteQuerAnalyzer_Linux_v${{ inputs.version }}_${{ inputs.architecture }}
        path: |
          src/project/SQLiteQueryAnalyzer.tar.gz
