name: Linux Build Template

on:
  workflow_call:
    inputs:
      version:
        description: 'Version number for the build'
        required: true
        type: string
      qt_version:
        description: 'Qt version to use'
        required: false
        default: '6.9.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Update Version in code
      shell: pwsh
      run: |
        $version = (Get-Content -Path src/project/CMakeLists.txt -Raw) -replace 'VERSION 1.0', 'VERSION "${{ inputs.version }}"'
        $version | Set-Content -Path src/project/CMakeLists.txt
        $version = (Get-Content -Path src/project/snapcraft.yaml -Raw) -replace 'version: 1.0.0', 'version: "${{ inputs.version }}"'
        $version | Set-Content -Path src/project/snapcraft.yaml
        $version = (Get-Content -Path src/main.cpp -Raw) -replace '#define VERSION "1.0.0"', '#define VERSION "${{ inputs.version }}"'
        $version | Set-Content -Path src/main.cpp
        cat src/main.cpp
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt_version }}
        
    - name: CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./linux .
        cmake --build . --config Release --parallel 32
        cmake --install .
      working-directory: src/project

    - name: Package
      run: |
        cpack -G 7Z
        cpack -G ZIP
        cpack -G TBZ2
        cpack -G TGZ
        cpack -G TXZ
        cpack -G TZ
        cpack -G DEB
        cpack -G RPM
      working-directory: src/project

    - name: Install Snap
      run: |
        sudo snap install lxd multipass
        sudo usermod -a -G lxd $USER
        sudo snap install snapcraft --classic

    - name: Initialize LXD 
      run: sudo lxd init --minimal
      working-directory: src/project
    
    - name: Build Snap Package
      run: snapcraft
      working-directory: src/project

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SQLiteQueryAnalyzer_Linux_v${{ inputs.version }}
        path: |
          src/project/SQLiteQueryAnalyzer-${{ inputs.version }}-Linux.*
          src/project/*.snap
