name: Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/linux.yml'
      - '!src/project/*'
      - '!src/**/*.cpp'
      - '!src/**/*.h'
      - '!src/**/*.ui'
    branches:
      - '*'

env:
  VERSION: '0.2.${{ github.run_number }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Version in code
      shell: pwsh
      run: |
        $version = (Get-Content -Path src/main.cpp -Raw) -replace '#define VERSION "1.0.0"', '#define VERSION "${{ env.VERSION }}"'
        $version | Set-Content -Path src/main.cpp
        cat src/main.cpp
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
    - name: QMake
      run: qmake
      working-directory: src/project
    - name: Make
      run: make -j 32
      working-directory: src/project
