name: MacOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/macos*.yml'
      - '!src/project/*'
      - '!src/**/*.cpp'
      - '!src/**/*.h'
      - '!src/**/*.ui'
    branches:
      - '*'

jobs:
  macos-arm64:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: '0.2.${{ github.run_number }}'
      os: 'macos-latest'
      architecture: 'arm64'
     
  macos-intel:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: '0.2.${{ github.run_number }}'
      os: 'macos-13'
      architecture: 'intel'
