name: MacOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/macos*.yml'
      - '!src/project/*'
      - '!src/**/*.cpp'
      - '!src/**/*.h'
    branches:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: '0.1.${{ github.run_number }}'