name: Build MacOS Template

on:
  workflow_call:
    inputs:
      version:
        description: 'Version number for the build'
        required: true
        type: string
      os:
        description: build agent
        required: true
        type: string
      architecture:
        description: cpu architecture
        required: true
        type: string
      build-qt:
        description: 'Build Qt from source and only include SQLite SQL driver'
        required: false
        type: boolean
        default: false

jobs:
  template:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
 
      - name: Update Version Number (Qt Project)
        shell: pwsh
        run: |
          $version = (Get-Content -Path src/project/SQLiteAnalyzer.pro -Raw) -replace 'VERSION = 1.0.0', 'VERSION = ${{ inputs.version }}'
          $version | Set-Content -Path src/project/SQLiteAnalyzer.pro

      - name: Update Version in code
        shell: pwsh
        run: |
          $version = (Get-Content -Path src/main.cpp -Raw) -replace '#define VERSION "1.0.0"', '#define VERSION "${{ inputs.version }}"'
          $version | Set-Content -Path src/main.cpp

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.0'

      - name: Build Qt from source
        if: ${{ inputs.build-qt }}
        run: |
          mkdir qt-build
          cd qt-build
          ../Qt/6.9.0/Src/configure -sql-sqlite
          cmake --build . --parallel
          sudo cmake --install .

      - name: QMake
        run: qmake
        working-directory: src/project

      - name: Make
        run: make -j 32
        working-directory: src/project

      - name: macdeployqt
        working-directory: src/project
        run: macdeployqt SQLiteQueryAnalyzer.app -dmg

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SQLiteQuerAnalyzer_MacOS_v${{ inputs.version }}_${{ inputs.architecture }}
          path: |
            src/project/SQLiteQueryAnalyzer.dmg
