name: MacOS

on:
  push:

env:
  VERSION: '0.1.${{ github.run_number }}'

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Version in code
      shell: pwsh
      run: |
        $version = (Get-Content -Path src/main.cpp -Raw) -replace '#define VERSION "1.0.0"', '#define VERSION "${{ env.VERSION }}"'
        $version | Set-Content -Path src/main.cpp
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
    - name: QMake
      run: qmake
      working-directory: src/project
    - name: Make
      run: make
      working-directory: src/project
    - name: macdeployqt
      working-directory: src/project
      run: macdeployqt SQLiteQueryAnalyzer.app -dmg
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SQLiteQuerAnalyzer_MacOS_v${{ env.VERSION }}
        path: |
          src/*.dmg
