name: Release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/release.yml'
    branches:
      - '*'

env:
  VERSION: '0.2.${{ github.run_number }}'

jobs:
  macos-arm64:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: '0.2.${{ github.run_number }}'
      os: macos-latest
      architecture: arm64
  macos-intel:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: '0.2.${{ github.run_number }}'
      os: macos-13
      architecture: intel
  windows:
    uses: ./.github/workflows/windows-template.yml
    with:
      version: 0.2.${{ github.run_number }}
      release: true
    secrets: inherit
  linux:
    uses: ./.github/workflows/linux-template.yml
    with:
      version: '0.2.${{ github.run_number }}'
  release:
    needs: [
      macos-arm64,
      macos-intel,
      windows,
      linux
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.VERSION }}",
              sha: context.sha
            })
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          draft: true
          prerelease: false
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Upload Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_Windows_Installer_v${{ env.VERSION }}/SQLiteQueryAnalyzer-Setup.exe
          asset_name: SQLiteQuerAnalyzer for Windows (Installer) v${{ env.VERSION }}.exe
          asset_content_type: application/zip
      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_Windows_v${{ env.VERSION }}/SQLiteQueryAnalyzer_Windows.zip
          asset_name: SQLiteQuerAnalyzer for Windows (Binaries) v${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload MacOS (ARM64) disk image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_MacOS_v${{ env.VERSION }}_arm64/SQLiteQueryAnalyzer.dmg
          asset_name: SQLiteQuerAnalyzer for MacOS (ARM64) v${{ env.VERSION }}.dmg
          asset_content_type: application/zip
      - name: Upload MacOS (Intel) disk image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_MacOS_v${{ env.VERSION }}_intel/SQLiteQueryAnalyzer.dmg
          asset_name: SQLiteQuerAnalyzer for MacOS (Intel) v${{ env.VERSION }}.dmg
          asset_content_type: application/zip
      - name: Upload Linux DEB Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQueryAnalyzer_Linux_v${{ env.VERSION }}/SQLiteQueryAnalyzer-${{ env.VERSION }}-Linux.deb
          asset_name: SQLiteQueryAnalyzer for Linux (DEB) v${{ env.VERSION }}.deb
          asset_content_type: application/octet-stream
      - name: Upload Linux RPM Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQueryAnalyzer_Linux_v${{ env.VERSION }}/SQLiteQueryAnalyzer-${{ env.VERSION }}-Linux.rpm
          asset_name: SQLiteQueryAnalyzer for Linux (RPM) v${{ env.VERSION }}.rpm
          asset_content_type: application/octet-stream
      - name: Upload Linux TGZ Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQueryAnalyzer_Linux_v${{ env.VERSION }}/SQLiteQueryAnalyzer-${{ env.VERSION }}-Linux.tar.gz
          asset_name: SQLiteQueryAnalyzer for Linux (TGZ) v${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
