name: Release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/release.yml'
    branches:
      - '*'

env:
  VERSION: '0.1.${{ github.run_number }}'

jobs:
  macos:
    uses: ./.github/workflows/macos-template.yml
    with:
      version: '0.1.${{ github.run_number }}'      
  windows:
    uses: ./.github/workflows/windows-template.yml
    with:
      version: 0.1.${{ github.run_number }}
      release: true
    secrets: inherit
  release:
    needs: [
      macos, 
      windows
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.VERSION }}",
              sha: context.sha
            })
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          draft: true
          prerelease: false
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Upload Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_Windows_Installer_v${{ env.VERSION }}/SQLiteQueryAnalyzer-Setup.exe
          asset_name: SQLiteQuerAnalyzer for Windows (Installer) v${{ env.VERSION }}.exe
          asset_content_type: application/zip
      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_Windows_v${{ env.VERSION }}/SQLiteQueryAnalyzer_Windows.zip
          asset_name: SQLiteQuerAnalyzer for Windows (Binaries) v${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload MacOS disk image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/SQLiteQuerAnalyzer_MacOS_v${{ env.VERSION }}/SQLiteQueryAnalyzer.dmg
          asset_name: SQLiteQuerAnalyzer for MacOS v${{ env.VERSION }}.dmg
          asset_content_type: application/zip
